name: 3D Contribution

on:
  schedule: # 03:00 KST == 18:00 UTC
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: ordme-yoo/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ ordem-yoo }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
